"""Riverwood (Skyrim) terrain as DDDA collision + waypoint graphs.

Usage: py skyterrain.py build AX AY AZ    anchor = Arisen GLOBAL position at the save
       py skyterrain.py install | restore   (game archives + the Skyrim plugin's ini)

`build` also writes DDDABridge_terrain.ini for the Skyrim plugin (terrain mode): the
same transform as the generated ground, as "sky x y z" = "dd x y z" (DDDA global).

Mapping (fixed): DDDA global (gx, gz) <-> Skyrim (sx, sy) with Riverwood's centre
(22528, -43008) at the centre of DD tiles m61..64 x n50..53 (20000, 130000), scale 100/70,
DD x = Skyrim x (east), DD z = -Skyrim y. Height: the ground under the anchor is
AY - 30 cm; everywhere else follows the Skyrim relative height, floored 1 m above
DDDA's sea level (only the riverbed is affected).
"""
import os
import shutil
import sys

import numpy as np

import spotcheck as sc
import synth_test

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "out_riverwood")
INI = "DDDABridge_terrain.ini"
SKYRIM_PLUGINS = r"E:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\SKSE\Plugins"
MS, NS = range(61, 65), range(50, 54)
MAX_SLOPE = 1.0  # 45 degrees between waypoint nodes


def sky_h_vec(sx, sy):
    i = sx / 128 - sc.cx0 * 32
    j = sy / 128 - sc.cy0 * 32
    i0, j0 = np.floor(i).astype(int), np.floor(j).astype(int)
    fi, fj = i - i0, j - j0
    H = sc.H
    return (H[j0, i0] * (1 - fi) * (1 - fj) + H[j0, i0 + 1] * fi * (1 - fj)
            + H[j0 + 1, i0] * (1 - fi) * fj + H[j0 + 1, i0 + 1] * fi * fj)


def base_y(ax, ay, az):
    """DDDA height of Skyrim height H0 (Riverwood centre's ground)."""
    return ay - 30.0 - sc.rel_cm(ax, az)


def make_height(ax, ay, az):
    base = base_y(ax, ay, az)

    def h(gx, gz):
        gx, gz = np.asarray(gx, dtype=np.float64), np.asarray(gz, dtype=np.float64)
        sx, sy = sc.to_sky(gx, gz)
        y = base + (sky_h_vec(sx, sy) - sc.H0) * sc.K
        return np.maximum(y, sc.SEA + 100.0)  # keep the riverbed out of DDDA's sea
    return h


if __name__ == "__main__":
    if sys.argv[1] == "build":
        ax, ay, az = map(float, sys.argv[2:5])
        h = make_height(ax, ay, az)
        g = np.meshgrid(np.arange(0, 40001, 200.0), np.arange(110000, 150001, 200.0))
        Y = h(*g)
        print(f"ground at anchor {float(h(ax, az)):.0f} (Arisen {ay:.0f}); region {Y.min():.0f}..{Y.max():.0f}; "
              f"lowest {(Y.min() - sc.SEA) / 100:+.1f} m vs DDDA sea")
        synth_test.build_region(h, MS, NS, OUT, {"anchor": [ax, ay, az]}, max_slope=MAX_SLOPE)
        with open(os.path.join(OUT, INI), "w") as f:
            f.write("# Skyrim point = DDDA global point; generated by tools/terrain/skyterrain.py\n")
            f.write(f"sky {sc.SKY_CENTER[0]:.3f} {sc.SKY_CENTER[1]:.3f} {float(sc.H0):.3f}\n")
            f.write(f"dd {sc.DD_CENTER[0]:.3f} {base_y(ax, ay, az):.3f} {sc.DD_CENTER[1]:.3f}\n")
        print(open(os.path.join(OUT, INI)).read())
    elif sys.argv[1] == "install":
        synth_test.install(OUT)
        shutil.copyfile(os.path.join(OUT, INI), os.path.join(SKYRIM_PLUGINS, INI))
        print("installed", os.path.join(SKYRIM_PLUGINS, INI))
    elif sys.argv[1] == "restore":
        synth_test.restore(OUT)
        if os.path.exists(os.path.join(SKYRIM_PLUGINS, INI)):
            os.remove(os.path.join(SKYRIM_PLUGINS, INI))
            print("removed", os.path.join(SKYRIM_PLUGINS, INI))
